alias dc   "docker-compose"
alias gg   "ghq get"
alias g    "git"
alias gitx "open -a GitX ."
alias r    "ranger"
alias rr   "ranger-cd"
alias vim  "begin; set -lx NVIM_TUI_ENABLE_TRUE_COLOR 1; nvim; end"
alias gmark "igo_bookmark"
alias dmark "idelete_bookmark"
alias smark "save_bookmark"
