FISH_TARGET_DIR=~/.config/fish

install:
	cp $(FISH_TARGET_DIR)/config.fish $(FISH_TARGET_DIR)/config.fish.backup
	cp $(FISH_TARGET_DIR)/fishfile $(FISH_TARGET_DIR)/fishfile.backup
	cp ./config.fish $(FISH_TARGET_DIR)/config.fish
	cp ./fishfile $(FISH_TARGET_DIR)/fishfile

get:
	cp $(FISH_TARGET_DIR)/config.fish ./config.fish
	cp $(FISH_TARGET_DIR)/fishfile ./fishfile
